### ISSUE TITLE
Windows usage

### ISSUE THREAD

**Issue by divix1988** [laminas/laminas-cli#10]
Can we add an information how to run laminas-cli commands on Windows machines?

The following seems to be working:
```
"vendor/bin/laminas-cli.bat" mvc:command
```

**Comment by arueckauer** [comment]
Can you provide some more information, like what you are trying to do and which system you are on?

`vendor\bin\laminas` works fine for me. Tested in cmd, PowerShell 5.1 and PowerShell 7.0 on Windows 10.0.19041.173.

**Comment by divix1988** [comment]
@arueckauer I am using latest XAMPP Shell window on Window 10.

**Comment by arueckauer** [comment]
Looks like, XAMPP is invoking a regular cmd. This is a known issue with cmd, please give `vendor\bin\laminas` a try or use e.g. a PowerShell, which can handle *nix directory separatory (`vendor/bin/laminas`).
