### ISSUE TITLE
Additional message for chained 3rd party commands

### ISSUE THREAD

**Issue by michalbundyra** [laminas/laminas-cli#26]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes

#### Summary

> Suggested before in: https://github.com/laminas/laminas-cli/pull/20#issuecomment-638685075.

When we provided chained commands there were some security concerns about it, so that's why before continuing execution of the next command we ask user to confirm - and there is ability to skip one command or break the chain.

I think it would be nice to clearly mark commands from 3rd party libraries, so user is aware that the command in chain is not laminas official command.

**Comment by weierophinney** [comment]
My concern is that if there is a way to mark the command as "official", any 3rd party library can likely do that as well, unless we have some signing capabilities of some sort... which gets very complicated.

Now, one thing I could potentially do: in the `TerminateListener`, we pull the next command. We could see if the namespace for that command instance is one of ours, and warn if not. Again, the potential issue is that somebody could still use our namespaces, but it would be trivial to do, and it's the same place where we prompt for the user to continue.

Would this work for you, @michalbundyra ?

**Comment by michalbundyra** [comment]
@weierophinney 

> We could see if the namespace for that command instance is one of ours, and warn if not. 

This is what I wanted to do. And yes - I do know the risk, but any other solution is to complex. Thanks
