### ISSUE TITLE
Add static analysis tool - preferably: psalm

### ISSUE THREAD

**Issue by michalbundyra** [laminas/laminas-cli#27]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes

#### Summary

We'd like to add static analysis tool - preferably psalm, so we can catch type issues easily.

**Comment by dev-loki** [comment]
Shall this PR directly fix all psalm issues or just add psalm support with baseline? :)

**Comment by weierophinney** [comment]
Fixed with #39.
