### ISSUE TITLE
Dev commands - additional commands configuration

### ISSUE THREAD

**Issue by michalbundyra** [laminas/laminas-cli#4]
We want provide some generic command configuration which will be easy to follow in any laminas-compatible package (laminas, mezzio etc...).

Do we need configuration for dev commands available only in dev mode?
Maybe it will just depend if the package is installed (`require` or `require-dev` section of `composer.json`)?

The first suggestion for the configuration will be as simple as:

```php
return [
   'cli' => [
        MyCommand::class,
    ],
];
```

Of course, if command `MyCommand` has dependencies factory should be registered in the container, so we can use:
```php
$container->get(MyCommand::class);
```

**Comment by geerteltink** [comment]
How about this:

```
return [
    'laminas-cli' => [
        'commands-dev' => [
            'package:dev-command-name' => MyDevCommand::class,
        ],
    ],
];
```

It should use the develop mode detection to enable or disable the commands.

**Comment by michalbundyra** [comment]
I think it is not needed for now. We might want to revisit it in the future if we decide that it could be useful.
