### ISSUE TITLE
3rd-party command notice message

### ISSUE THREAD

**Issue by michalbundyra** [laminas/laminas-cli#44]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 0.1.3+

#### Summary

In #37 we have added message about executing 3rd party commands.
In my opinion, per https://github.com/laminas/laminas-cli/pull/37#discussion_r463391626 comment, it should not be added for local commands - defined in the project.

We can check local commands by checking namespaces defined in `autoload(-dev)` sections of `composer.json`.

#### Current behavior

We are adding the notice for all non-Laminas commands atm.

#### How to reproduce

Create any local command, use it in a chain and run the command with a chain.

#### Expected behavior

We should skip the message for local commands.

**Comment by weierophinney** [comment]
Fixed with #53
