### ISSUE TITLE
Log command errors

### ISSUE THREAD

**Issue by vaclavvanik** [laminas/laminas-cli#47]
### Feature Request

Now is not possible to [log command errors](https://symfony.com/doc/current/console.html#logging-command-errors).

`ApplicationFactory` creates own [EventDispatcher](https://github.com/laminas/laminas-cli/blob/30f9426ea6448ee1a7e813c87862381a489b8e71/src/ApplicationFactory.php#L43) and it is not possible to add custom listener.

Maybe EventDispatcher could be grabbed from service container, so dev could inject custom EventDispatcher with custom listeners.

**Comment by weierophinney** [comment]
Fixed with #54
