### ISSUE TITLE
Param normalization not applied during invocation

### ISSUE THREAD

**Issue by jbh** [laminas/laminas-cli#55]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 0.1.5

#### Summary

_When using IntParam, normalization doesn't seem to be applied on invocation, contrary to laminas-cli documentation._

I'm using IntParam like so:

```php
protected function configure() : void
{
    $this->setName(self::$defaultName);
    $this->addParam(
        (new IntParam('id'))
        ->setDescription('Order identity key')
        ->setShortcut('k')
        ->setDefault(15)
    );
}
```

When I invoke the command with `-k 15`, I get the error:

```
In Assert.php line 2042:

  Invalid value: integer expected, string given


order:get [-k|--id ID]
```

If I don't invoke with the option and pass it via the prompted question, normalization is applied. I tested by adding output to the normalizer and validator and executing the command both ways:

```
$ ./vendor/bin/laminas order:get -k 15
string(13) "validating..."

In Assert.php line 2042:

  Invalid value: integer expected, string given


order:get [-k|--id ID]
```

Note how above, while passing the parameter during invocation, it just shows `validating...`.

```
$ ./vendor/bin/laminas order:get
Order identity key: [15]
 > 15
string(14) "normalizing..."
string(13) "validating..."

Order Identity Key #15
======================

 --------- ---------- ------------- ---------- ---------- ------ ------- --------
  Order #   Subtotal   Fulfillment   Handling   Discount   Tax    Total   Status
 --------- ---------- ------------- ---------- ---------- ------ ------- --------
  test      test       test          test       test       test   test    test
 --------- ---------- ------------- ---------- ---------- ------ ------- --------
```

Note how above, while passing the parameter via question, `normalizing...` happens before validation.

#### How to reproduce

Configure a command with an IntParam and try calling it while sending the parameter on command line.

#### Expected behavior

According to the [documentation](https://docs.laminas.dev/laminas-cli/command-params/), the normalizer should be applied during invocation. I'm assuming invocation means passing the parameter while calling the command. I could be misunderstanding, though.

> If the parameter has validations or normalizations supplied, these will be applied regardless of whether the option is provided during invocation or when the user is prompted to provide it.

**Comment by weierophinney** [comment]
Fixed with #58
