### ISSUE TITLE
Add support for Symfony v6

### ISSUE THREAD

**Issue by internalsystemerror** [laminas/laminas-cli#86]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    | no

#### Summary

Add support for the newly released Symfony v6 packages specifically `symfony/event-dispatcher` and `symfony/console`.

**Comment by froschdesign** [comment]
@internalsystemerror 
Do you know any problems with the new version of the Symfony components?

**Comment by internalsystemerror** [comment]
Just the ones mentioned in the PR description. There is a contract change:

`InputInterface::isInteractive(): ?bool` is now `InputInterface::isInteractive(): bool`

and the `Question` class no longer allows mutliple default values to be passed as an array, only a scalar value. I'm operating on the belief that a multiline default value is how that "should" be done instead.

I've tested this branch in my own components with no issues, however none are using the multiple default values where this change would affect them.
