### ISSUE TITLE
Replace composer/package-versions-deprecated with composer-runtime-api

### ISSUE THREAD

**Issue by internalsystemerror** [laminas/laminas-cli#89]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    | no

#### Summary

Due to the need to support PHP 7.3, `ocramius/package-versions` was replaced with `composer/package-versions-deprecated`. ([Issue](https://github.com/laminas/laminas-cli/issues/35), [PR](https://github.com/laminas/laminas-cli/pull/36)). Since support for PHP 7.3 has now been dropped, I'd like to propose moving to `composer-runtime-api` as per https://getcomposer.org/doc/07-runtime.md#knowing-the-version-of-package-x.

Are there any thoughts on this? I can submit the PR if accepted.

**Comment by Ocramius** [comment]
Let's roll with `composer-runtime-api` :+1:

**Comment by Ocramius** [comment]
Thanks @internalsystemerror!
