### ISSUE TITLE
Command autocomplete

### ISSUE THREAD

**Issue by michalbundyra** [laminas/laminas-cli#9]
Adds implementation for autocompleting command names as suggested by @akrabat

**Comment by michalbundyra** [comment]
I am not sure if we can do it better than:
https://github.com/bamarni/symfony-console-autocomplete

It is not something what is gonna work for all systems and it needs additional configuration in the system. We might want to add something to the documentation, how to enable command autocomplete, but I wouldn't treat at as a priority for now.

Please note, it is not even implemented in symfony/console itself.

**Comment by weierophinney** [comment]
I actually like the idea of us just providing documentation on how to use that library — particularly if we can potentially address installing it to work with whatever is in `$PWD/vendor/bin/laminas` (as that will give you project-specific completion).
